require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-md

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    # - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  # Max: 20
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
